spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.210:1116/YLDB
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: yl2012
    password: yl.Q.ACL
  redis:
    host: 192.168.1.210
    port: 5000
    timeout: 2000
    database: 0